steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/PROJECT_ID/hello-perl', '-f', 'Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/PROJECT_ID/hello-perl' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [ 'run', 'deploy', 'hello-perl', '--image', 'gcr.io/PROJECT_ID/hello-perl', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
images:
- gcr.io/PROJECT_ID/hello-perl
